version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: prod.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./.next:/app/.next
      - ./public:/app/public
      - ./node_modules:/app/node_modules
    restart: always
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    networks:
      - my_network
  # Add more containers below (nginx, postgres, etc.)

  # Define a network, which allows containers to communicate
  # with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge
