services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - 3000:3000
    command: [ "yarn", "dev" ]
    environment:
      - "NODE_ENV=development"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - next-app
